email: kevin@erabond.io
full_name: Kevin Mead
name: Kevin
background: Kevin is the CEO of Erabond, a HubSpot CRM Development agency. They specialize in building CRMs that support sales, marketing, and service teams.
schedule_preferences: By default, unless specified otherwise, you should make meetings 30 minutes long.
background_preferences:
response_preferences:
timezone: "PST"
rewrite_preferences: |
  Kevin has a few rules for how he likes his emails to be written:
  - He generally likes to match their tone. If they write formally, then so will he. If they write casually, then he should write casual
  - If working with an assistant to schedule, then he is usually more formal
  - If conversing with someone he seems to know well, then he is more direct and to the fact
  - Kevin REALLY does not want anyone to know he is using an assistant, so you should try not to sound too much like an assistant and rather sound like Kevin
  - When Kevin is casual, he generally does not include any greetings or sign offs, and just directly says his message
triage_no: |
  - Automated emails from services that are spamming Kevin
  - Cold outreach from vendors - this happens a lot as people try to sell Kevin things. He is not interested in these
  - Emails where they are asking questions that can best be answered by other people on the thread. \
  Kevin is often on a lot of threads with people from his company (Erabond) but often times he does not need to chime in. \
  The exception to this is if Kevin is the main driver of the conversation. \
  You can usually tell this by whether Kevin was the one who sent the last email
  - Notifications of comments on Google Docs
  - Automated calendar invitations
triage_notify: |
  - Google docs that were shared with him (do NOT notify him on comments, just net new ones)
  - Sales meeting requests
  - Emails where there is a clear action item from Harrison based on a previous conversation, like adding people to a slack channel
triage_email: |
  - Emails from clients that explicitly ask Kevin a question
  - Emails from clients where someone else has scheduled a meeting for Kevin, and Kevin has not already chimed in to express his excitement
  - Emails from clients or potential customers where Kevin is the main driver of the conversation
  - Emails from other Erabond team members that explicitly ask Kevin a question
  - Emails where Kevin has gotten added to a thread with a customer and he hasn't yet said hello
  - Email from clients where they are trying to set up a time to meet
  - Emails where it seems like Kevin has a pre-existing relationship with the sender. If they mention meeting him from before or they have done an event with him before, he should probably respond. If it seems like they are referencing an event or a conversation they had before, Kevin should probably respond. 
  - Emails from friends - even these don't ask an explicit question, if it seems like something a good friend would respond to, Harrison should do so.

  Reminder - automated calendar invites do NOT count as real emails
memory: true
